---
NONMEM_directory: C:\nm75g64
NONMEM_version: 7.5
PsN_version: 5.3.1
command_line: C:\PsN-5.3.1\strawberry\perl\bin/execute 1cmt_iv_est_covar_r_matrix.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 3
  compress: 0
  condition_number_limit: 1000
  correlation_limit: 0.85
  crash_restarts: 5
  debug_rmd: 0
  degree: 0.1
  directory: C:\Users\mklose\Desktop\GitHub\personal-website\posts\understanding_nlme_estimation\models\estimation\modelfit_dir2\
  display_iterations: 1
  handle_crashes: 1
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: -99
  model_subdir: 0
  near_bound_sign_digits: 2
  near_zero_boundary_limit: 0.01
  nice: 19
  nm_output: 'ext,cov,cor,coi,phi,phm,cnv,smt,rmt,npd,npe,npi,npl,ets'
  nm_version: default
  nmfe: 1
  nodes: 0
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 500203
  send_email: 0
  shrinkage: 0
  sign_digits_off_diagonals: 2
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: C:/PsN-5.3.1/strawberry/perl/site/lib/PsN_5_3_1/R-scripts
  template_file_rplots: execute_default.Rmd
  threads: 5
  tweak_inits: 1
  verbose: 0
  zip: 1
copied_files:
  - 1cmt_iv_est_covar_r_matrix.lst
  - 1cmt_iv_est_covar_r_matrix.ext
  - 1cmt_iv_est_covar_r_matrix.cov
  - 1cmt_iv_est_covar_r_matrix.cor
  - 1cmt_iv_est_covar_r_matrix.coi
  - 1cmt_iv_est_covar_r_matrix.phi
  - estim_out_covar_r_matrix
finish_time: 2025-01-16 13:49:30
model_files:
  - C:\Users\mklose\Desktop\GitHub\personal-website\posts\understanding_nlme_estimation\models\estimation\1cmt_iv_est_covar_r_matrix.mod
start_time: 2025-01-16 13:49:17
tool_name: execute
tool_options:
  copy_data: 1
  prepend_options_to_lst: 0
  tail_output: 0
R_version: 4.3.0
R_system: x86_64, mingw32
R_packages:
  - cli-3.6.3 from CRAN (R 4.3.3)
  - codetools-0.2-19 from CRAN (R 4.3.0)
  - colorspace-2.1-0 from CRAN (R 4.3.1)
  - digest-0.6.36 from CRAN (R 4.3.3)
  - dplyr-1.1.4 from CRAN (R 4.3.2)
  - evaluate-0.23 from CRAN (R 4.3.2)
  - fansi-1.0.6 from CRAN (R 4.3.2)
  - fastmap-1.1.1 from CRAN (R 4.3.1)
  - foreach-1.5.2 from CRAN (R 4.3.1)
  - gam-1.22-2 from CRAN (R 4.3.1)
  - generics-0.1.3 from CRAN (R 4.3.1)
  - ggplot2-3.5.1 from CRAN (R 4.3.3)
  - glue-1.7.0 from CRAN (R 4.3.3)
  - gtable-0.3.4 from CRAN (R 4.3.0)
  - htmltools-0.5.8.1 from CRAN (R 4.3.3)
  - htmlwidgets-1.6.4 from CRAN (R 4.3.2)
  - iterators-1.0.14 from CRAN (R 4.3.1)
  - jsonlite-1.8.8 from CRAN (R 4.3.2)
  - knitr-1.46 from CRAN (R 4.3.3)
  - lattice-0.21-8 from CRAN (R 4.3.0)
  - lifecycle-1.0.4 from CRAN (R 4.3.2)
  - magrittr-2.0.3 from CRAN (R 4.3.1)
  - munsell-0.5.0 from CRAN (R 4.3.1)
  - pillar-1.9.0 from CRAN (R 4.3.1)
  - pkgconfig-2.0.3 from CRAN (R 4.3.1)
  - PsNR-0.2.1 from Github (UUPharmacometrics/PsNR@12e42cc74c0962527212e6ae59e958c52b765a7e)
  - R6-2.5.1 from CRAN (R 4.3.1)
  - rlang-1.1.4 from CRAN (R 4.3.3)
  - rmarkdown-2.26 from CRAN (R 4.3.3)
  - scales-1.3.0 from CRAN (R 4.3.2)
  - sessioninfo-1.2.2 from CRAN (R 4.3.1)
  - tibble-3.2.1 from CRAN (R 4.3.1)
  - tidyselect-1.2.1 from CRAN (R 4.3.3)
  - utf8-1.2.4 from CRAN (R 4.3.1)
  - vctrs-0.6.5 from CRAN (R 4.3.3)
  - xfun-0.45 from CRAN (R 4.3.3)
  - xpose4-4.7.2 from CRAN (R 4.3.1)
  - yaml-2.3.9 from CRAN (R 4.3.3)
R_LIB_PATHS:
  - C:/Program Files/R/Library
  - C:/Program Files/R/R-4.3.0/library
