---
title: "TLD-1, a novel liposomal doxorubicin, in patients with advanced solid tumors: Dose escalation and expansion part of a multicenter open-label phase I trial (SAKK 65/16)"
description: "European Journal of Cancer"
author:
  - name: "Colombo I, Koster KL, Holer L, Haefliger S, Rabaglio M, Bastian S, Schwitter M, Eckhardt K, Hayoz S, Mc Laughlin AM, Kloft C, **Klose M**, Halbherr S, Baumgartner C, Sessa C, Stathis A, Hess D, Joerger M."
date: 02-02-2024 # mm dd yyyy
categories: [Middle author, TLD-1, PEGylated liposomal doxorubicin, Doxorubicin, Safety, Efficacy, NCA]
Type: Publication
Journal: "*European Journal of Cancer*"
doi: 10.1016/j.ejca.2024.113588
draft: false 
echo: true
execute:
  echo: true
  message: false
  warning: false
format:
  html:
    number-sections: false
    toc: false
    code-fold: false
    code-tools: false
comments: false
---

## Abstract 

### Background
TLD-1 is a novel liposomal doxorubicin that compared favorably to conventional doxorubicin liposomal formulations in preclinical models. This phase I first-in-human study aimed to define the maximum tolerated dose (MTD), recommended phase 2 dose (RP2D), safety and preliminary activity of TLD-1 in patients with advanced solid tumors.

### Patients and methods
We recruited patients with advanced solid tumors who failed standard therapy and received up to 3 prior lines of palliative systemic chemotherapy. TLD-1 was administered intravenously every 3 weeks up to a maximum of 9 cycles (6 for patients with prior anthracyclines) from a starting dose of 10 mg/m2, according to an accelerated titration design followed by a modified continual reassessment method.

### Results
30 patients were enrolled between November 2018 and May 2021. No dose-limiting toxicities (DLT) were observed. Maximum administered dose of TLD-1 was 45 mg/m2, RP2D was defined at 40 mg/m2. Most frequent treatment-related adverse events (TRAE) of any grade included palmar-plantar erythrodysesthesia (PPE) (50% of patients), oral mucositis (50%), fatigue (30%) and skin rash (26.7%). Most common G3 TRAE included PPE in 4 patients (13.3%) and oral mucositis in 2 (6.7%). Overall objective response rate was 10% in the whole population and 23.1% among 13 patients with breast cancer; median time-to-treatment failure was 2.7 months. TLD-1 exhibit linear pharmacokinetics, with a median terminal half-life of 95 h.

### Conclusions
The new liposomal doxorubicin formulation TLD-1 showed a favourable safety profile and antitumor activity, particularly in breast cancer. RP2D was defined at 40 mg/m2 administered every 3 weeks. (NCT03387917)

