---
title: "The Impact of UGT2B7 and CYP2D6 Gene-Drug- and CYP-mediated Drug-Drug-Interactions on Oxycodone and Oxymorphone Pharmacokinetics using PBPK Modelling."
description: "ACoP13"
author:
  - name: "**Klose M**, Schmidt S, Cristofoletti R."
date: 10-30-2022 # mm dd yyyy
categories: [PBPK, Oxycodone, GDI, DDI, UGT2B7, CYP2D6, First author]
Type: Abstract
Journal: "*ACoP13*"
draft: false 
echo: true
execute:
  echo: true
  message: false
  warning: false
format:
  html:
    number-sections: false
    toc: false
    code-fold: false
    code-tools: false
comments: false
---

## URL

<https://www.go-acop.org/?abstract=413>

## Abstract

### Objectives

Oxycodone, a widely used opioid to treat moderate to severe pain, is subject of pharmacogenomic debate. After CYP2D6 mediated formation of oxymorphone (60 times higher μ-opioid receptor affinity than the parent [1]) it undergoes conjugation via UGT2B7. Two polymorphic enzymes are involved in this path, which may lead to high variability in oxymorphone exposure and response. In addition, 45% of the dose is metabolized to noroxycodone via CYP3A4. A recent publication by the Clinical Pharmacogenetics Implementation Consortium stated that there is 'insufficient evidence' to guide clinical practice at the moment [2]. Hence, the objective of our work was to investigate the impact of CYP2D6 and UGT2B7 gene-drug-interactions (GDI) and CYP-mediated drug-drug-interactions (DDI) on the PK of oxycodone using PBPK modelling.

### Methods

GastroPlus 9.8.2 was used to build a PBPK model in a bottom-up approach. Drug-specific parameters were derived from reported in vitro or in vivo data; otherwise, in silico predictions were used. Vmax values were optimized to match reported mass balance and urinary excretion data. For the wild type UGT2B7H and the mutated allele UGT2B7Y, Vmax and Km values from literature [3] were weighted by the prevalence of the genotype. The verified PBPK models were applied to interrogate the impact of combined GDI and DDI on oxycodone and its metabolites exposures. The impact of such interactions was assessed by comparing drug exposure (AUC) in each simulated scenario versus oxycodone and metabolites AUCs in a CYP2D6 and UGT2B7 normal metabolizer without comedication.

### Results

97% of predicted AUC values for oxycodone and its metabolites were within a 1.5-fold error range. In clinical DDI studies 95% of changes in AUC metabolite-to-parent-ratios were predicted within a 2.0-fold error range. Simulation results indicate that CYP2D6 ultrarapid metabolizers (UM) / UGT2B7 poor metabolizers (PM) have a 2.1-fold higher AUC for oxymorphone compared with normal metabolizers (NM). In CYP2D6 PM / UGT2B7 NM the AUC for oxymorphone was decreased by 3.1-fold and the AUC for oxycodone was increased by 1.2-fold. The highest exposure was predicted for CYP2D6 UM / UGT2B7 PM receiving a single dose of 400 mg ketoconazole. A 2.6-fold AUC increase for oxycodone and a 4.3-fold AUC increase for oxymorphone was predicted. The lowest exposure is expected for CYP2D6 PM / UGT2B7 NM receiving 600 mg rifampicin QD. The AUC for oxycodone decreased 5.8-fold and the AUC of oxymorphone decreased 21.1-fold.

### Conclusions

So far, variability in oxycodone PKPD was attempted to be explained by CYP2D6 GDIs or DDIs alone. However, our research shows that not only the formation of oxymorphone but also the metabolism of oxymorphone via UGT2B7 should be considered. Some groups – especially in combined GDI and DDI scenarios – are expected to have significant over- or underexposure. For example, a CYP2D6 UM and UGT2B7 PM has high formation of oxymorphone and low clearance, which may lead to accumulation. These effects are amplified in DDI settings and should be considered in practice.

### Citations

[1] Volpe et al. (2011) Regulatory Toxicology and Pharmacology (59) 

[2] Crews et al. (2021) Clinical Pharmacology & Therapeutics (110) 

[3] Coffman et.al. (1998) Drug Metab Dispos (26) 