#!/usr/bin/env python3
"""
Build publications.qmd from publications.json.

Usage:
    python constructor.py

Reads ./publications.json (relative to this script) and writes
./publications.qmd with every entry baked in as plain markdown.
No JavaScript, no fetch, no custom CSS — Quarto's theme handles styling.

Entries are grouped by section (## heading) and by year (### subheading)
within each section, sorted newest-first.

Edit the JSON, re-run this script, then `quarto preview` / `quarto render`.
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).parent
JSON_PATH = HERE / "publications.json"
QMD_PATH = HERE / "publications.qmd"

# (Heading shown in qmd, type value in JSON)
SECTIONS: list[tuple[str, str]] = [
    ("Papers", "publication"),
    ("Abstracts/Posters",          "abstract"),
    ("Presentations",              "presentation"),
]

YAML_HEADER = """\
---
title: "Publications"
toc: true
format:
  html:
    css: styles.css
    toc: false
comments: false
---

<!-- AUTO-GENERATED by constructor.py from publications.json — do not edit by hand. -->
"""

EMPTY_PLACEHOLDER = "_No entries yet._"


def format_date(iso: str) -> str:
    """Convert ISO date 'YYYY-MM-DD' to 'Mon YYYY' for display."""
    y, m, d = map(int, iso.split("-"))
    return date(y, m, d).strftime("%b %Y")


def render_entry(pub: dict) -> str:
    """
    Render one publication as a markdown paragraph:

        **Title**
        Authors (with **Klose M** kept bold from the JSON)
        *Journal* · Mon YYYY · [doi: ...](https://doi.org/...)
    """
    title_line = f"**{pub['title']}**"
    author_line = pub["authors"]  # already contains markdown **bold** for own name

    meta: list[str] = []
    if pub.get("journal"):
        meta.append(f"*{pub['journal']}*")
    meta.append(format_date(pub["date"]))

    if pub.get("doi"):
        doi = pub["doi"]
        meta.append(f"[doi: {doi}](https://doi.org/{doi})")
    elif pub.get("url"):
        meta.append(f"[Link]({pub['url']})")

    meta_line = " · ".join(meta)
    return f"{title_line}.\n{author_line}.\n{meta_line}"


def main() -> int:
    if not JSON_PATH.exists():
        print(f"Error: {JSON_PATH} not found.", file=sys.stderr)
        return 1

    try:
        items = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"Error parsing {JSON_PATH.name}: {exc}", file=sys.stderr)
        return 1

    # Newest first — this drives both year order and within-year order.
    items.sort(key=lambda p: p["date"], reverse=True)

    chunks: list[str] = [YAML_HEADER]
    counts: dict[str, int] = {}

    for heading, type_ in SECTIONS:
        chunks.append(f"\n## {heading}\n")
        subset = [p for p in items if p["type"] == type_]
        counts[type_] = len(subset)

        if not subset:
            chunks.append(f"\n{EMPTY_PLACEHOLDER}\n")
            continue

        # Group by year. `subset` inherits the global newest-first sort,
        # so each new year appears in descending order and entries within
        # a year stay sorted by date desc.
        current_year: str | None = None
        for pub in subset:
            year = pub["date"][:4]
            if year != current_year:
                chunks.append(f"\n#### {year}\n")
                current_year = year
            chunks.append("\n" + render_entry(pub) + "\n")

    QMD_PATH.write_text("".join(chunks), encoding="utf-8")

    total = sum(counts.values())
    print(f"Wrote {total} entries to {QMD_PATH.name}:")
    for _, type_ in SECTIONS:
        print(f"  {type_:>14}: {counts.get(type_, 0)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
