---
title: "Publications"
toc: false
---

## 2024

- **Klose M**, Cristofoletti R, Silva CM, Mangal N, Turgeon J, Michaud V, Lesko LJ, Schmidt S. Exploring the impact of CYP2D6 and UGT2B7 gene-drug interactions, and CYP-mediated DDI on oxycodone and oxymorphone pharmacokinetics using physiologically-based pharmacokinetic modeling and simulation. *Eur J Pharm Sci*. 2024 Mar 1;194:106689. doi: [10.1016/j.ejps.2023.106689](https://www.doi.org/10.1016/j.ejps.2023.106689). Epub 2024 Jan 1. PMID: 38171419.
- Colombo I, Koster KL, Holer L, Haefliger S, Rabaglio M, Bastian S, Schwitter M, Eckhardt K, Hayoz S, Mc Laughlin AM, Kloft C, **Klose M**, Halbherr S, Baumgartner C, Sessa C, Stathis A, Hess D, Joerger M. TLD-1, a novel liposomal doxorubicin, in patients with advanced solid tumors: Dose escalation and expansion part of a multicenter open-label phase I trial (SAKK 65/16). *Eur J Cancer*. 2024 Apr;201:113588. doi: [10.1016/j.ejca.2024.113588](https://www.doi.org/10.1016/j.ejca.2024.113588). Epub 2024 Feb 2. PMID: 38377773.


## 2021

- Liebchen U, **Klose M**, Paal M, Vogeser M, Zoller M, Schroeder I, Schmitt L, Huisinga W, Michelet R, Zander J, Scharf C, Weinelt FA, Kloft C. Evaluation of the MeroRisk Calculator, A User-Friendly Tool to Predict the Risk of Meropenem Target Non-Attainment in Critically Ill Patients. *Antibiotics (Basel)*. 2021 Apr 20;10(4):468. doi: [10.3390/antibiotics10040468](https://www.doi.org/10.3390/antibiotics10040468). PMID: 33924047; PMCID: PMC8074046.



# Abstracts/Posters

## 2022

- **Klose M**, Schmidt S, Cristofoletti R. The Impact of UGT2B7 and CYP2D6 Gene-Drug- and CYP-mediated Drug-Drug-Interactions on Oxycodone and Oxymorphone Pharmacokinetics using PBPK Modelling. *ACoP13 (2022) PBPK-413*. Available from: [www.go-acop.org/?abstract=413](www.go-acop.org/?abstract=413). Physiologically Based Pharmacokinetics.

## 2021

- Michelet R, Weinelt FA, **Klose M**, Mc Laughlin AM, Kluwe F, Montefusco-Pereira C, Van Dyk M, Vay M, Huisinga W, Kloft C, Mikus G. Using microdose-based activity measurement to individualise dosing of cytochrome P450 metabolised drugs: a case study with yohimbine and tamoxifen. *PAGE 2021*: Clinical Applications. Available from: [https://www.page-meeting.org/default.asp?abstract=9807](https://www.page-meeting.org/default.asp?abstract=9807).

