---
NONMEM_directory: C:\nm76g64
NONMEM_version: 7.6
PsN_version: 5.5.0
command_line: C:\PsN-5.5.0\strawberry\perl\bin/execute 1cmt_iv_map_est.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 3
  compress: 0
  crash_restarts: 5
  debug_rmd: 0
  degree: 0.1
  directory: C:\Users\mklose\Desktop\GitHub\personal-website\posts\bayes_map_estimation_r\models\modelfit_dir2\
  display_iterations: 1
  handle_crashes: 1
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: -99
  model_subdir: 0
  nice: 19
  nm_output: 'ext,cov,cor,coi,phi,phm,cnv,smt,rmt,npd,npe,npi,npl,ets'
  nm_version: default
  nmfe: 1
  nodes: 0
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 296753
  send_email: 0
  shrinkage: 0
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: C:/PsN-5.5.0/strawberry/perl/site/lib/PsN_5_5_0/R-scripts
  template_file_rplots: execute_default.Rmd
  threads: 5
  tweak_inits: 1
  verbose: 0
  zip: 1
copied_files:
  - 1cmt_iv_map_est.lst
  - 1cmt_iv_map_est.ext
  - 1cmt_iv_map_est.phi
  - map_estim_out
finish_time: 2025-03-31 11:43:56
model_files:
  - C:\Users\mklose\Desktop\GitHub\personal-website\posts\bayes_map_estimation_r\models\1cmt_iv_map_est.mod
start_time: 2025-03-31 11:43:48
tool_name: execute
tool_options:
  copy_data: 1
  prepend_options_to_lst: 0
  tail_output: 0
